#!/bin/bash

if [[ -f $HOME/.config/dmenurc ]]; then
	. $HOME/.config/dmenurc
else
	DMENU="dmenu -i"
fi

ARTIST=$( mpc ls | $DMENU )

if [[ $ARTIST == "" ]]; then
	exit 1
else
	ALBUM=$( echo -e "Play All\n$( mpc ls "$ARTIST" )" | $DMENU )
	if [[ $ALBUM == "" ]]; then
		exit 1
	else
		mpc clear
		
		if [[ $ALBUM == "Play All" ]]; then
			mpc add "$ARTIST"
		else
			mpc add "$ALBUM"
		fi
		mpc play
	fi
fi

exit 0
