#!/bin/bash

# Pay attention, because the destination of the radiolist is hard-coded
select=`~/scripts/radiostation/radiolist | awk -F $'\t' '{printf "%s\n", $1}' | dmenu` ;

if [ "$select" == "stop" ]; then
mpc stop ;
exit 0 ;
fi

while read info; do


	name=`echo "$info" | awk -F $'\t' '{printf "%s", $1}'` ;
	file=`echo "$info" | awk -F $'\t' '{printf "%s", $2}'` ;

	if [ "$select" == "$name" ]; then
		mpc clear ;
		mpc add $file ;
		mpc play ;
	fi

done < ~/scripts/radiostation/radiolist
